spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring?useSSL=true
    username: root
    password: S1st3m45
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true 
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        
  thymeleaf:
    cache: false